//
//  Overview.swift
//  College Website
//
//  Created by Atharva Padekar on 09/08/23.
//

import Foundation

struct Overview: Codable {
    let symbol: String
    let assetType: String
    let name: String
    let description: String
    let cik: String
    let exchange: String
    let currency: String
    let country: String
    let sector: String
    let industry: String
    let address: String
    let fiscalYearEnd: String
    let latestQuarter: String
    let marketCapitalization: String
    let ebitda: String
    let peRatio: String
    let pegRatio: String
    let bookValue: String
    let dividendPerShare: String
    let dividendYield: String
    let eps: String
    let revenuePerShareTtm: String
    let profitMargin: String
    let operatingMarginTtm: String
    let returnOnAssetsTtm: String
    let returnOnEquityTtm: String
    let revenueTtm: String
    let grossProfitTtm: String
    let dilutedEpsTtm: String
    let quarterlyEarningsGrowthYoy: String
    let quarterlyRevenueGrowthYoy: String
    let analystTargetPrice: String
    let trailingPe: String
    let forwardPe: String
    let priceToSalesRatioTtm: String
    let priceToBookRatio: String
    let evToRevenue: String
    let evToEbitda: String
    let beta: String
    let weekHigh: String
    let weekLow: String
    let dayMovingAverage50: String
    let dayMovingAverage200: String
    //let dayMovingAverage: String
    //let dayMovingAverage: String
    let sharesOutstanding: String
    let dividendDate: String
    let exDividendDate: String

    enum CodingKeys: String, CodingKey {
        case symbol = "Symbol"
        case assetType = "AssetType"
        case name = "Name"
        case description = "Description"
        case cik = "CIK"
        case exchange = "Exchange"
        case currency = "Currency"
        case country = "Country"
        case sector = "Sector"
        case industry = "Industry"
        case address = "Address"
        case fiscalYearEnd = "FiscalYearEnd"
        case latestQuarter = "LatestQuarter"
        case marketCapitalization = "MarketCapitalization"
        case ebitda = "EBITDA"
        case peRatio = "PERatio"
        case pegRatio = "PEGRatio"
        case bookValue = "BookValue"
        case dividendPerShare = "DividendPerShare"
        case dividendYield = "DividendYield"
        case eps = "EPS"
        case revenuePerShareTtm = "RevenuePerShareTTM"
        case profitMargin = "ProfitMargin"
        case operatingMarginTtm = "OperatingMarginTTM"
        case returnOnAssetsTtm = "ReturnOnAssetsTTM"
        case returnOnEquityTtm = "ReturnOnEquityTTM"
        case revenueTtm = "RevenueTTM"
        case grossProfitTtm = "GrossProfitTTM"
        case dilutedEpsTtm = "DilutedEPSTTM"
        case quarterlyEarningsGrowthYoy = "QuarterlyEarningsGrowthYOY"
        case quarterlyRevenueGrowthYoy = "QuarterlyRevenueGrowthYOY"
        case analystTargetPrice = "AnalystTargetPrice"
        case trailingPe = "TrailingPE"
        case forwardPe = "ForwardPE"
        case priceToSalesRatioTtm = "PriceToSalesRatioTTM"
        case priceToBookRatio = "PriceToBookRatio"
        case evToRevenue = "EVToRevenue"
        case evToEbitda = "EVToEBITDA"
        case beta = "Beta"
        case weekHigh = "52WeekHigh"
        case weekLow = "52WeekLow"
        case dayMovingAverage50 = "50DayMovingAverage"
        case dayMovingAverage200 = "200DayMovingAverage"
        case sharesOutstanding = "SharesOutstanding"
        case dividendDate = "DividendDate"
        case exDividendDate = "ExDividendDate"
    }
}

//{
//    "Symbol": "IBM",
//    "AssetType": "Common Stock",
//    "Name": "International Business Machines",
//    "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
//    "CIK": "51143",
//    "Exchange": "NYSE",
//    "Currency": "USD",
//    "Country": "USA",
//    "Sector": "TECHNOLOGY",
//    "Industry": "COMPUTER & OFFICE EQUIPMENT",
//    "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
//    "FiscalYearEnd": "December",
//    "LatestQuarter": "2023-06-30",
//    "MarketCapitalization": "131403514000",
//    "EBITDA": "12985000000",
//    "PERatio": "61.12",
//    "PEGRatio": "1.276",
//    "BookValue": "24.37",
//    "DividendPerShare": "6.61",
//    "DividendYield": "0.046",
//    "EPS": "2.36",
//    "RevenuePerShareTTM": "66.75",
//    "ProfitMargin": "0.0335",
//    "OperatingMarginTTM": "0.141",
//    "ReturnOnAssetsTTM": "0.0411",
//    "ReturnOnEquityTTM": "0.104",
//    "RevenueTTM": "60524999000",
//    "GrossProfitTTM": "32688000000",
//    "DilutedEPSTTM": "2.36",
//    "QuarterlyEarningsGrowthYOY": "0.126",
//    "QuarterlyRevenueGrowthYOY": "-0.004",
//    "AnalystTargetPrice": "130.37",
//    "TrailingPE": "61.12",
//    "ForwardPE": "15.55",
//    "PriceToSalesRatioTTM": "2.108",
//    "PriceToBookRatio": "6.75",
//    "EVToRevenue": "2.969",
//    "EVToEBITDA": "25.81",
//    "Beta": "0.855",
//    "52WeekHigh": "149.31",
//    "52WeekLow": "111.29",
//    "50DayMovingAverage": "135.23",
//    "200DayMovingAverage": "134.83",
//    "SharesOutstanding": "911006000",
//    "DividendDate": "2023-09-09",
//    "ExDividendDate": "2023-08-09"
//}
